### ISSUE TITLE
get_celex errors

### ISSUE THREAD

**Issue by alexeykosh** [rycolab/homophony-as-renyi-entropy#1]
When I am trying to run the get_celex command, I get the following error:

```
touch ./data/celex/raw//LDC96L14//extracted.txt
touch: ./data/celex/raw//LDC96L14//extracted.txt: No such file or directory
make: *** [data/celex/raw//LDC96L14//extracted.txt] Error 1
```

I did compress my celex folder and put in the specified dir. Here is the structure of the celex folder that I am using:

```
LDC96L14
├── celex_intro.pdf
├── dutch
│   ├── README
│   ├── dab
│   ├── dct
│   ├── dfl
│   ├── dfs
│   ├── dfw
│   ├── dml
│   ├── dmw
│   ├── dol
│   ├── dow
│   ├── dpl
│   ├── dpw
│   ├── dsl
│   ├── dug_a4.ps
│   └── dug_let.ps
├── english
│   ├── README.txt
│   ├── ect
│   ├── efl
│   ├── efs
│   ├── efw
│   ├── eml
│   ├── emw
│   ├── eol
│   ├── eow
│   ├── epl
│   ├── epw
│   ├── esl
│   ├── eug_a4.ps
│   ├── eug_let.pdf
│   └── eug_let.ps
├── extracted.txt
└── german
    ├── README
    ├── gct
    ├── gfl
    ├── gfw
    ├── gml
    ├── gmw
    ├── gol
    ├── gow
    ├── gpl
    ├── gpw
    ├── gsl
    ├── gug_a4.ps
    └── gug_let.ps
```

Do you know how I can fix that to run your code?

**Comment by tpimentelms** [comment]
Hey @alexeykosh , are you sure the `LDC96L14.tar.gz` file was put into the relative path `data/celex/raw/`? Also, are you running the code from the project's main directory?

It seems to be working fine here when I do:
```bash
$ cd homophony-as-renyi-entropy/
$ mv ~/Downloads/LDC96L14.tar.gz data/celex/raw/
$ make get_celex
```

**Comment by alexeykosh** [comment]
Hi @tpimentelms! Yes, I am sure, also I am doing it from the main directory as you suggested. It still does not work... Maybe you can share the CELEX files that you're using?
